source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/BJComponent/BJSpecs.git'

use_frameworks!

platform :ios, '8.0'

target 'FFSpecialKit_Example' do
  pod 'FFSpecialKit', :path => '../'
  
  pod 'Masonry'
  pod 'YYWebImage'
#  pod 'ReactiveCocoa', '~> 2.5'
  
  pod 'FFAPIs', '~> 0.1.2'
  pod 'FFUtils', '~> 0.1.3'
  pod 'FFWdiget', git:'https://github.com/BJComponent/FFWdiget.git'
  
  pod 'FFAuhtorKit_Category'

  target 'FFSpecialKit_Tests' do
    inherit! :search_paths

    
  end
end
